apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/part-of: operator
  name: rhtas-operator
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhtas-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhtas-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:30f6c6666a8807362f70a7d01345d9cfaf92ce7e61d29ca3996cd4787b8b5229
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
status: {}
