apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtas-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:e1323e892b6216fb6ec7805a96d8200a9f5a94e67001e85036183d8926e27ea7
        name: container-image
        resources: {}
status: {}
