apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtas-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:47e068408e42979531208872a461810c6a39db45e0ec4732cc56bf25a8a9e1bc
        name: container-image
        resources: {}
status: {}
