apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtas-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:69bb37d91d0701236a2ae5e028aceb0aad7aac646c666f5744bb481058509e0c
        name: container-image
        resources: {}
status: {}
