apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtas-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/operator/rhtas-operator@sha256:11b081f7f891ab934ccdb37a41b165266cb8c03509f48aba036c269d0f0aef79
        name: container-image
        resources: {}
status: {}
